[project]
name = 'upgradable-fungible-token'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'
requirements = []
[contracts.upgradable-fungible-token]
path = 'contracts/upgradable-fungible-token.clar'
clarity_version = 2
epoch = 2.5

[contracts.upgradable-fungible-token-logic]
path = 'contracts/upgradable-fungible-token-logic.clar'
clarity_version = 2
epoch = 2.5

[contracts.upgradable-fungible-token-logic-pausing]
path = 'contracts/upgradable-fungible-token-logic-pausing.clar'
clarity_version = 2
epoch = 2.5

[contracts.upgradable-fungible-token-logic-trait]
path = 'contracts/upgradable-fungible-token-logic-trait.clar'
clarity_version = 2
epoch = 2.5

[contracts.upgradable-fungible-token-trait]
path = 'contracts/upgradable-fungible-token-trait.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
